<upgrade>
    <user_group_settings>
        <setting>
            <is_admin_setting>0</is_admin_setting>
            <module_id>share</module_id>
            <type>boolean</type>
            <admin>1</admin>
            <user>1</user>
            <guest>0</guest>
            <staff>1</staff>
            <module>share</module>
            <ordering>0</ordering>
            <value>can_share_items</value>
        </setting>
    </user_group_settings>
</upgrade>