<?php
return function (Phpfox_Installer $Installer) {
    $installerDb = $Installer->db;

    $iCnt = $installerDb->select('component_id')
        ->from(':component')
        ->where([
            'component' => 'users-you-may-know',
            'module_id' => 'user',
        ])
        ->execute('getField');
    if (empty($iCnt)) {
        $installerDb->insert(':component', [
            'component' => 'users-you-may-know',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_controller' => '0',
            'is_block' => '1',
            'is_active' => '1',
        ]);
    }

    $iCnt = $installerDb->select('component_id')
        ->from(':component')
        ->where([
            'component' => 'recently-active',
            'module_id' => 'user',
        ])
        ->execute('getField');
    if (empty($iCnt)) {
        $installerDb->insert(':component', [
            'component' => 'recently-active',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_controller' => '0',
            'is_block' => '1',
            'is_active' => '1',
        ]);
    }

    $iCnt = $installerDb->select('block_id')
        ->from(':block')
        ->where([
            'm_connection' => 'user.browse',
            'module_id' => 'user',
            'component' => 'users-you-may-know',
        ])
        ->execute('getField');
    if (empty($iCnt)) {
        $installerDb->insert(':block', [
            'title' => 'Users You May Know',
            'type_id' => '0',
            'm_connection' => 'user.browse',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'component' => 'users-you-may-know',
            'location' => '2',
            'is_active' => '1',
            'ordering' => '1',
            'can_move' => '0',
        ]);
    }

    $iCnt = $installerDb->select('block_id')
        ->from(':block')
        ->where([
            'm_connection' => 'user.browse',
            'module_id' => 'user',
            'component' => 'recently-active',
        ])
        ->execute('getField');
    if (empty($iCnt)) {
        $installerDb->insert(':block', [
            'title' => 'Recently Active',
            'type_id' => '0',
            'm_connection' => 'user.browse',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'component' => 'recently-active',
            'location' => '2',
            'is_active' => '1',
            'ordering' => '2',
            'can_move' => '0',
        ]);
    }

    $aNewSettings = [
        [
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => 'string',
            'var_name' => 'redirect_after_logout',
            'value_default' => '',
            'phrase_var_name' => 'setting_redirect_after_logout',
            'ordering' => 3,
        ],
        [
            'group_id' => 'registration',
            'module_id' => 'core',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => 'boolean',
            'var_name' => 'enable_register_with_google',
            'phrase_var_name' => 'setting_enable_register_with_google',
            'value_actual' => '0',
            'value_default' => '0',
            'ordering' => 22,
        ],
        [
            'group_id' => 'registration',
            'module_id' => 'core',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => 'string',
            'var_name' => 'google_oauth_client_id',
            'phrase_var_name' => 'setting_google_oauth_client_id',
            'value_actual' => '',
            'value_default' => '',
            'ordering' => 23,
        ],
        [
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => '0',
            'version_id' => '4.8.4',
            'type_id' => 'boolean',
            'var_name' => 'enable_feed_user_update_profile',
            'value_actual' => '1',
            'value_default' => '1',
            'phrase_var_name' => 'setting_enable_feed_user_update_profile',
            'ordering' => 4,
        ],
        [
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => 'boolean',
            'var_name' => 'enable_feed_user_update_relationship',
            'value_actual' => '1',
            'value_default' => '1',
            'phrase_var_name' => 'setting_enable_feed_user_update_relationship',
            'ordering' => 5,
        ],
        //New User email setting
        [
            'group_id' => 'email',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'user_setting_subject_pending_approval_user',
            'value_actual' => '{_p var="pending_approval"}',
            'value_default' => '{_p var="pending_approval"}',
            'phrase_var_name' => 'setting_user_setting_subject_pending_approval_user',
            'ordering' => 4,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'user_setting_content_pending_approval_user',
            'value_actual' => '{_p var="we_are_reviewing_your_account_and_pending_approval"}',
            'value_default' => '{_p var="we_are_reviewing_your_account_and_pending_approval"}',
            'phrase_var_name' => 'setting_user_setting_content_pending_approval_user',
            'ordering' => 5,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'user_setting_subject_approve_user',
            'value_actual' => '{_p var="account_approved"}',
            'value_default' => '{_p var="account_approved"}',
            'phrase_var_name' => 'setting_user_setting_subject_approve_user',
            'ordering' => 6,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'user_setting_content_approve_user',
            'value_actual' => '{_p var="your_account_has_been_approved_on_site_title"}',
            'value_default' => '{_p var="your_account_has_been_approved_on_site_title"}',
            'phrase_var_name' => 'setting_user_setting_content_approve_user',
            'ordering' => 7,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'user_setting_subject_deny_user',
            'value_actual' => '{_p var="deny_mail_subject"}',
            'value_default' => '{_p var="deny_mail_subject"}',
            'phrase_var_name' => 'setting_user_setting_subject_deny_user',
            'ordering' => 8,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'user_setting_content_deny_user',
            'value_actual' => '{_p var="deny_mail_message"}',
            'value_default' => '{_p var="deny_mail_message"}',
            'phrase_var_name' => 'setting_user_setting_content_deny_user',
            'ordering' => 9,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'user_setting_subject_inactive_user',
            'value_actual' => '{_p var="inactive_member_email_subject"}',
            'value_default' => '{_p var="inactive_member_email_subject"}',
            'phrase_var_name' => 'setting_user_setting_subject_inactive_user',
            'ordering' => 10,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'user_setting_content_inactive_user',
            'value_actual' => '{_p var="inactive_member_email_body"}',
            'value_default' => '{_p var="inactive_member_email_body"}',
            'phrase_var_name' => 'setting_user_setting_content_inactive_user',
            'ordering' => 11,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'user_setting_subject_like_status',
            'value_actual' => '{_p var="full_name_liked_your_status_update_content"}',
            'value_default' => '{_p var="full_name_liked_your_status_update_content"}',
            'phrase_var_name' => 'setting_user_setting_subject_like_status',
            'ordering' => 12,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'user_setting_content_like_status',
            'value_actual' => '{_p var="full_name_liked_your_status_update_message"}',
            'value_default' => '{_p var="full_name_liked_your_status_update_message"}',
            'phrase_var_name' => 'setting_user_setting_content_like_status',
            'ordering' => 13,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'user_setting_subject_like_another_status',
            'value_actual' => '{_p var="full_name_liked_full_name2_status_update"}',
            'value_default' => '{_p var="full_name_liked_full_name2_status_update"}',
            'phrase_var_name' => 'setting_user_setting_subject_like_another_status',
            'ordering' => 14,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'user_setting_content_like_another_status',
            'value_actual' => '{_p var="full_name_liked_full_name2_status_update_message"}',
            'value_default' => '{_p var="full_name_liked_full_name2_status_update_message"}',
            'phrase_var_name' => 'setting_user_setting_content_like_another_status',
            'ordering' => 15,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'user_setting_subject_comment_on_other_user_status',
            'value_actual' => '{_p var="full_name_commented_on_one_of_other_full_name_s_status_updates"}',
            'value_default' => '{_p var="full_name_commented_on_one_of_other_full_name_s_status_updates"}',
            'phrase_var_name' => 'setting_user_setting_subject_comment_on_other_user_status',
            'ordering' => 16,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'user_setting_content_comment_on_other_user_status',
            'value_actual' => '{_p var="full_name_commented_on_other_full_name_s_status_update_a_href_link_title_a_to_see_the_comment_thread_follow_the_link_below_a_href_link_link_a"}',
            'value_default' => '{_p var="full_name_commented_on_other_full_name_s_status_update_a_href_link_title_a_to_see_the_comment_thread_follow_the_link_below_a_href_link_link_a"}',
            'phrase_var_name' => 'setting_user_setting_content_comment_on_other_user_status',
            'ordering' => 17,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'user_setting_subject_imported_user',
            'value_actual' => '{_p var="import_user_send_mail_title"}',
            'value_default' => '{_p var="import_user_send_mail_title"}',
            'phrase_var_name' => 'setting_user_setting_subject_imported_user',
            'ordering' => 18,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'user_setting_content_imported_user',
            'value_actual' => '{_p var="import_user_send_mail_content"}',
            'value_default' => '{_p var="import_user_send_mail_content"}',
            'phrase_var_name' => 'setting_user_setting_content_imported_user',
            'ordering' => 19,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'user_setting_subject_welcome_user',
            'value_actual' => '{_p var="welcome_email_subject"}',
            'value_default' => '{_p var="welcome_email_subject"}',
            'phrase_var_name' => 'setting_user_setting_subject_welcome_user',
            'ordering' => 20,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'user_setting_content_welcome_user',
            'value_actual' => '{_p var="welcome_email_content"}',
            'value_default' => '{_p var="welcome_email_content"}',
            'phrase_var_name' => 'setting_user_setting_content_welcome_user',
            'ordering' => 21,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'user_setting_subject_tagged_on_status',
            'value_actual' => '{_p var="user_name_tagged_you_in_a_status_update"}',
            'value_default' => '{_p var="user_name_tagged_you_in_a_status_update"}',
            'phrase_var_name' => 'setting_user_setting_subject_tagged_on_status',
            'ordering' => 22,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'user_setting_content_tagged_on_status',
            'value_actual' => '{_p var="user_name_tagged_you_in_a_status_update_check_it_out"}',
            'value_default' => '{_p var="user_name_tagged_you_in_a_status_update_check_it_out"}',
            'phrase_var_name' => 'setting_user_setting_content_tagged_on_status',
            'ordering' => 23,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'user_setting_subject_comment_on_owner_status',
            'value_actual' => '{_p var="full_name_commented_on_your_status_update"}',
            'value_default' => '{_p var="full_name_commented_on_your_status_update"}',
            'phrase_var_name' => 'setting_user_setting_subject_comment_on_owner_status',
            'ordering' => 24,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'user_setting_content_comment_on_owner_status',
            'value_actual' => '{_p var="full_name_commented_on_your_status_update_title_to_see_the_comment_thread_follow_the_link_below_a_href_link_link_a"}',
            'value_default' => '{_p var="full_name_commented_on_your_status_update_title_to_see_the_comment_thread_follow_the_link_below_a_href_link_link_a"}',
            'phrase_var_name' => 'setting_user_setting_content_comment_on_owner_status',
            'ordering' => 25,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'user_setting_subject_comment_on_their_own_status',
            'value_actual' => '{_p var="full_name_commented_on_one_of_gender_status_updates"}',
            'value_default' => '{_p var="full_name_commented_on_one_of_gender_status_updates"}',
            'phrase_var_name' => 'setting_user_setting_subject_comment_on_their_own_status',
            'ordering' => 26,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'user',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'user_setting_content_comment_on_their_own_status',
            'value_actual' => '{_p var="full_name_commented_on_gender_status_update_a_href_link_title_a_to_see_the_comment_thread_follow_the_link_below_a_href_link_link_a"}',
            'value_default' => '{_p var="full_name_commented_on_gender_status_update_a_href_link_title_a_to_see_the_comment_thread_follow_the_link_below_a_href_link_link_a"}',
            'phrase_var_name' => 'setting_user_setting_content_comment_on_their_own_status',
            'ordering' => 27,
        ],
        //New Report email setting
        [
            'group_id' => 'email',
            'module_id' => 'report',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'report_setting_subject_report_is_processed',
            'value_actual' => '{_p var="your_report_is_processed"}',
            'value_default' => '{_p var="your_report_is_processed"}',
            'phrase_var_name' => 'setting_report_setting_subject_report_is_processed',
            'ordering' => 1,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'report',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'report_setting_content_report_is_processed',
            'value_actual' => '{_p var="your_report_for_item_link_is_processed"}',
            'value_default' => '{_p var="your_report_for_item_link_is_processed"}',
            'phrase_var_name' => 'setting_report_setting_content_report_is_processed',
            'ordering' => 2,
        ],
        //New Link email setting
        [
            'group_id' => 'email',
            'module_id' => 'link',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'link_setting_subject_like_user_link',
            'value_actual' => '{_p var="full_name_liked_your_link_title"}',
            'value_default' => '{_p var="full_name_liked_your_link_title"}',
            'phrase_var_name' => 'setting_link_setting_subject_like_user_link',
            'ordering' => 1,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'link',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'link_setting_content_like_user_link',
            'value_actual' => '{_p var="full_name_liked_your_link_title_message"}',
            'value_default' => '{_p var="full_name_liked_your_link_title_message"}',
            'phrase_var_name' => 'setting_link_setting_content_like_user_link',
            'ordering' => 2,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'link',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'link_setting_subject_comment_user_link',
            'value_actual' => '{_p var="full_name_commented_on_your_link_title"}',
            'value_default' => '{_p var="full_name_commented_on_your_link_title"}',
            'phrase_var_name' => 'setting_link_setting_subject_comment_user_link',
            'ordering' => 3,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'link',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'link_setting_content_comment_user_link',
            'value_actual' => '{_p var="full_name_commented_on_your_link_a_href_link_title_a"}',
            'value_default' => '{_p var="full_name_commented_on_your_link_a_href_link_title_a"}',
            'phrase_var_name' => 'setting_link_setting_content_comment_user_link',
            'ordering' => 4,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'link',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'link_setting_subject_comment_their_own_link',
            'value_actual' => '{_p var="full_name_commented_on_gender_link"}',
            'value_default' => '{_p var="full_name_commented_on_gender_link"}',
            'phrase_var_name' => 'setting_link_setting_subject_comment_their_own_link',
            'ordering' => 5,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'link',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'link_setting_content_comment_their_own_link',
            'value_actual' => '{_p var="full_name_commented_on_gender_link_a_href_link_title_a"}',
            'value_default' => '{_p var="full_name_commented_on_gender_link_a_href_link_title_a"}',
            'phrase_var_name' => 'setting_link_setting_content_comment_their_own_link',
            'ordering' => 6,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'link',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'link_setting_subject_comment_other_link',
            'value_actual' => '{_p var="full_name_commented_on_row_full_name_s_link"}',
            'value_default' => '{_p var="full_name_commented_on_row_full_name_s_link"}',
            'phrase_var_name' => 'setting_link_setting_subject_comment_other_link',
            'ordering' => 7,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'link',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'link_setting_content_comment_other_link',
            'value_actual' => '{_p var="full_name_commented_on_row_full_name_s_link_a_href_link_title_a_message"}',
            'value_default' => '{_p var="full_name_commented_on_row_full_name_s_link_a_href_link_title_a_message"}',
            'phrase_var_name' => 'setting_link_setting_content_comment_other_link',
            'ordering' => 8,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'link',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'link_setting_subject_add_link_on_user_wall',
            'value_actual' => '{_p var="full_name_posted_a_link_on_your_wall"}',
            'value_default' => '{_p var="full_name_posted_a_link_on_your_wall"}',
            'phrase_var_name' => 'setting_link_setting_subject_add_link_on_user_wall',
            'ordering' => 9,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'link',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'link_setting_content_add_link_on_user_wall',
            'value_actual' => '{_p var="full_name_posted_a_link_on_your_wall_message"}',
            'value_default' => '{_p var="full_name_posted_a_link_on_your_wall_message"}',
            'phrase_var_name' => 'setting_link_setting_content_add_link_on_user_wall',
            'ordering' => 10,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'link',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'link_setting_subject_tagged_on_link',
            'value_actual' => '{_p var="full_name_tagged_you_in_a_link"}',
            'value_default' => '{_p var="full_name_tagged_you_in_a_link"}',
            'phrase_var_name' => 'setting_link_setting_subject_tagged_on_link',
            'ordering' => 11,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'link',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'link_setting_content_tagged_on_link',
            'value_actual' => '{_p var="full_name_tagged_you_in_a_link_you_can_view_here"}',
            'value_default' => '{_p var="full_name_tagged_you_in_a_link_you_can_view_here"}',
            'phrase_var_name' => 'setting_link_setting_content_tagged_on_link',
            'ordering' => 12,
        ],
        //New Invite email setting
        [
            'group_id' => 'email',
            'module_id' => 'invite',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'invite_setting_subject_invited_to_site',
            'value_actual' => '{_p var="full_name_invites_you_to_site_title"}',
            'value_default' => '{_p var="full_name_invites_you_to_site_title"}',
            'phrase_var_name' => 'setting_invite_setting_subject_invited_to_site',
            'ordering' => 1,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'invite',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'invite_setting_content_invited_to_site',
            'value_actual' => '{_p var="full_name_invites_you_to_site_title_link"}',
            'value_default' => '{_p var="full_name_invites_you_to_site_title_link"}',
            'phrase_var_name' => 'setting_invite_setting_content_invited_to_site',
            'ordering' => 2,
        ],
        //New Friend email setting
        [
            'group_id' => 'email',
            'module_id' => 'friend',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'friend_setting_subject_sent_friend_request',
            'value_actual' => '{_p var="full_name_added_you_as_a_friend_on_site_title"}',
            'value_default' => '{_p var="full_name_added_you_as_a_friend_on_site_title"}',
            'phrase_var_name' => 'setting_friend_setting_subject_sent_friend_request',
            'ordering' => 1,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'friend',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'friend_setting_content_sent_friend_request',
            'value_actual' => '{_p var="full_name_added_you_as_a_friend_on_site_title_to_confirm_this_friend_request"}',
            'value_default' => '{_p var="full_name_added_you_as_a_friend_on_site_title_to_confirm_this_friend_request"}',
            'phrase_var_name' => 'setting_friend_setting_content_sent_friend_request',
            'ordering' => 2,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'friend',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'friend_setting_subject_added_as_friend',
            'value_actual' => '{_p var="full_name_added_you_as_a_friend_on_site_title"}',
            'value_default' => '{_p var="full_name_added_you_as_a_friend_on_site_title"}',
            'phrase_var_name' => 'setting_friend_setting_subject_added_as_friend',
            'ordering' => 3,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'friend',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'friend_setting_content_added_as_friend',
            'value_actual' => '{_p var="full_name_added_you_as_a_friend_on_site_title_to_view_the_profile_of_this_friend_follow_the_link_below_link"}',
            'value_default' => '{_p var="full_name_added_you_as_a_friend_on_site_title_to_view_the_profile_of_this_friend_follow_the_link_below_link"}',
            'phrase_var_name' => 'setting_friend_setting_content_added_as_friend',
            'ordering' => 4,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'friend',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'friend_setting_subject_confirmed_friend_request',
            'value_actual' => '{_p var="full_name_confirmed_you_as_a_friend_on_site_title"}',
            'value_default' => '{_p var="full_name_confirmed_you_as_a_friend_on_site_title"}',
            'phrase_var_name' => 'setting_friend_setting_subject_confirmed_friend_request',
            'ordering' => 5,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'friend',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'friend_setting_content_confirmed_friend_request',
            'value_actual' => '{_p var="full_name_confirmed_you_as_a_friend_on_site_title_to_view_their_profile"}',
            'value_default' => '{_p var="full_name_confirmed_you_as_a_friend_on_site_title_to_view_their_profile"}',
            'phrase_var_name' => 'setting_friend_setting_content_confirmed_friend_request',
            'ordering' => 6,
        ],
        //New Feed email setting
        [
            'group_id' => 'email',
            'module_id' => 'feed',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'feed_setting_subject_comment_on_own_post_on_other_wall',
            'value_actual' => '{_p var="full_name_commented_on_one_of_gender_wall_comments"}',
            'value_default' => '{_p var="full_name_commented_on_one_of_gender_wall_comments"}',
            'phrase_var_name' => 'setting_feed_setting_subject_comment_on_own_post_on_other_wall',
            'ordering' => 1,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'feed',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'feed_setting_content_comment_on_own_post_on_other_wall',
            'value_actual' => '{_p var="full_name_commented_on_one_of_gender_wall_comments_message"}',
            'value_default' => '{_p var="full_name_commented_on_one_of_gender_wall_comments_message"}',
            'phrase_var_name' => 'setting_feed_setting_content_comment_on_own_post_on_other_wall',
            'ordering' => 2,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'feed',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'feed_setting_subject_comment_on_post_on_other_wall',
            'value_actual' => '{_p var="full_name_commented_on_one_of_row_full_name_s_wall_comments"}',
            'value_default' => '{_p var="full_name_commented_on_one_of_row_full_name_s_wall_comments"}',
            'phrase_var_name' => 'setting_feed_setting_subject_comment_on_post_on_other_wall',
            'ordering' => 3,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'feed',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'feed_setting_content_comment_on_post_on_other_wall',
            'value_actual' => '{_p var="full_name_commented_on_one_of_row_full_name_s_wall_comments_message"}',
            'value_default' => '{_p var="full_name_commented_on_one_of_row_full_name_s_wall_comments_message"}',
            'phrase_var_name' => 'setting_feed_setting_content_comment_on_post_on_other_wall',
            'ordering' => 4,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'feed',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'feed_setting_subject_comment_on_post_on_your_wall',
            'value_actual' => '{_p var="full_name_commented_on_one_of_your_wall_comments"}',
            'value_default' => '{_p var="full_name_commented_on_one_of_your_wall_comments"}',
            'phrase_var_name' => 'setting_feed_setting_subject_comment_on_post_on_your_wall',
            'ordering' => 5,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'feed',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'feed_setting_content_comment_on_post_on_your_wall',
            'value_actual' => '{_p var="full_name_commented_on_one_of_your_wall_comments_to_see_the_comment_thread_follow_the_link_below_a_href_link_link_a"}',
            'value_default' => '{_p var="full_name_commented_on_one_of_your_wall_comments_to_see_the_comment_thread_follow_the_link_below_a_href_link_link_a"}',
            'phrase_var_name' => 'setting_feed_setting_content_comment_on_post_on_your_wall',
            'ordering' => 6,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'feed',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'feed_setting_subject_like_your_post_on_other_wall',
            'value_actual' => '{_p var="full_name_liked_a_comment_you_posted_on_row_full_name_s_wall"}',
            'value_default' => '{_p var="full_name_liked_a_comment_you_posted_on_row_full_name_s_wall"}',
            'phrase_var_name' => 'setting_feed_setting_subject_like_your_post_on_other_wall',
            'ordering' => 7,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'feed',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'feed_setting_content_like_your_post_on_other_wall',
            'value_actual' => '{_p var="full_name_liked_your_comment_message"}',
            'value_default' => '{_p var="full_name_liked_your_comment_message"}',
            'phrase_var_name' => 'setting_feed_setting_content_like_your_post_on_other_wall',
            'ordering' => 8,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'feed',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'feed_setting_subject_like_your_comments',
            'value_actual' => '{_p var="full_name_liked_one_of_your_comments"}',
            'value_default' => '{_p var="full_name_liked_one_of_your_comments"}',
            'phrase_var_name' => 'setting_feed_setting_subject_like_your_comments',
            'ordering' => 9,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'feed',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'feed_setting_content_like_your_comments',
            'value_actual' => '{_p var="full_name_liked_your_comment_message_mini"}',
            'value_default' => '{_p var="full_name_liked_your_comment_message_mini"}',
            'phrase_var_name' => 'setting_feed_setting_content_like_your_comments',
            'ordering' => 10,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'feed',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'feed_setting_subject_other_post_on_your_wall',
            'value_actual' => '{_p var="full_name_wrote_a_comment_on_your_wall"}',
            'value_default' => '{_p var="full_name_wrote_a_comment_on_your_wall"}',
            'phrase_var_name' => 'setting_feed_setting_subject_other_post_on_your_wall',
            'ordering' => 11,
        ],
        [
            'group_id' => 'email',
            'module_id' => 'feed',
            'product_id' => 'phpfox',
            'is_hidden' => 0,
            'version_id' => '4.8.4',
            'type_id' => '',
            'var_name' => 'feed_setting_content_other_post_on_your_wall',
            'value_actual' => '{_p var="full_name_wrote_a_comment_on_your_wall_message"}',
            'value_default' => '{_p var="full_name_wrote_a_comment_on_your_wall_message"}',
            'phrase_var_name' => 'setting_feed_setting_content_other_post_on_your_wall',
            'ordering' => 12,
        ],
    ];

    foreach ($aNewSettings as $aNewSetting) {
        $checkSetting = $installerDb->select('setting_id')
            ->from(':setting')
            ->where([
                'var_name' => $aNewSetting['var_name'],
                'module_id' => $aNewSetting['module_id']
            ])->executeRow();
        if (!$checkSetting) {
            $installerDb->insert(':setting', $aNewSetting);
        }
    }

    //Update IP Address Field
    $listIpFields = [
        'admincp_login' => ['ip_address', false],
        'api_gateway_log' => 'ip_address',
        'comment_rating' => 'ip_address',
        'log_session' => ['ip_address', false],
        'log_staff' => ['ip_address', false],
        'log_view' => ['ip_address', false],
        'report_data' => ['ip_address', false],
        'track' => ['ip_address', false],
        'upload_track' => ['ip_address', false],
        'user' => 'last_ip_address',
        'user_blocked' => 'ip_address',
        'user_ip' => ['ip_address', false],
        'user_verify_error' => ['ip_address', false],
    ];
    foreach ($listIpFields as $table => $field) {
        $tableName = Phpfox::getT($table);
        $allowNull = true;
        if (is_array($field) && count($field) == 2) {
            $field = $field[0];
            $allowNull = !!$field[1];
        }
        if ($installerDb->tableExists($tableName) && $installerDb->isField($tableName, $field)) {
            $installerDb->query("ALTER TABLE `{$tableName}` CHANGE `{$field}` `{$field}` VARCHAR(50) " . ($allowNull ? "DEFAULT NULL;" : "NOT NULL;"));
        }
    }

    // add new user group settings
    $aNewUserGroupSettings = [
        'can_invite_friends' => [
            'module' => 'invite',
            'name' => 'can_invite_friends',
            'user_group' => [
                '1' => 1,
                '2' => 1,
                '3' => 0,
                '4' => 1,
                '5' => 0,
            ],
            'options' => [
                "yes" => "Yes",
                "no" => "No",
            ],
            'product_id' => 'phpfox',
            'type' => 'boolean',
            'text' => 'Can invite friends?',
        ],
    ];

    $aLanguages = Phpfox::getService('language')->getAll();
    foreach ($aNewUserGroupSettings as $aNewUserGroupSetting) {
        $sNormalText = $aNewUserGroupSetting['text'];
        $aNewUserGroupSetting['text'] = [];
        foreach ($aLanguages as $aLanguage) {
            $aNewUserGroupSetting['text'][$aLanguage['language_code']] = $sNormalText;
        }
        Phpfox::getService('user.group.setting.process')->addSetting($aNewUserGroupSetting);
    }

    $tableName = Phpfox::getT('component');
    if (!$installerDb->isField($tableName, 'allowed_connections')) {
        $installerDb->addField([
            'table' => $tableName,
            'field' => 'allowed_connections',
            'type' => 'MEDIUMTEXT',
            'null' => true,
        ]);
    }

    $aUpdatePhrases = [
        "custom_relation_single_new"                     => "Is single",
        "custom_relation_single_with"                    => "Is single",
        "user_is_no_longer_listed_as"                    => "Is no longer listed as \"{previous}\"",
        "custom_relation_engaged_new"                    => "Is engaged",
        "custom_relation_engaged_with"                   => "Is engaged to {with_full_name}",
        "custom_relation_married_with"                   => "Is married to {with_full_name}",
        "custom_relation_married_new"                    => "Is married",
        "custom_relation_it_s_complicated_new"           => "Is in a relationship and it's complicated",
        "custom_relation_it_s_complicated_with"          => "Is in a complicated relationship with {with_full_name}",
        "custom_relation_in_an_open_relationship_new"    => "Is in an open relationship",
        "custom_relation_in_an_open_relationship_with"   => "Is in an open relationship with {with_full_name}",
        "custom_relation_widowed_new"                    => "Is widowed",
        "custom_relation_custom_relation_separated_with" => "Is no longer with {with_full_name}",
        "custom_relation_custom_relation_separated_new"  => "Is no longer with {with_full_name}",
        "custom_relation_separated_with"                 => "Is no longer with {with_full_name}",
        "custom_relation_separated_new"                  => "Is no longer with {with_full_name}",
        "custom_relation_divorced_with"                  => "Is now divorced",
        "custom_relation_cheating_with"                  => "Is cheating on his relationship with {with_full_name}",
        "custom_relation_cheating_new"                   => "Is being unfaithful",
        "custom_relation_blank_with"                     => "Is no longer listed as {previous_status}",
        "custom_relation_in_a_relationship"              => "In a relationship",
        "custom_relation_in_a_relationship_with"         => "Is in a relationship with {with_full_name}",
        "custom_relation_in_a_relationship_new"          => "Is in a relationship",
        "relation_went_from_old_status_to_new_status"    => "Went from being \"{sOldStatus}\" to \"{sNewStatus}\"",
    ];

    Phpfox::getService('language.phrase.process')->updatePhrases($aUpdatePhrases);

    $tableName = Phpfox::getT('attachment');
    if (!$installerDb->isField($tableName, 'location')) {
        $installerDb->addField([
            'table' => $tableName,
            'field' => 'location',
            'type' => 'VCHAR:50',
            'null' => true,
        ]);
    }
};