<upgrade>
    <setting_groups>
        <name>
            <module_id>core</module_id>
            <version_id>4.8.4</version_id>
            <var_name>setting_group_emails</var_name>
            <value>email</value>
        </name>
    </setting_groups>
</upgrade>