<upgrade>
    <user_group_settings>
        <setting>
            <is_admin_setting>0</is_admin_setting>
            <module_id>user</module_id>
            <type>boolean</type>
            <admin>1</admin>
            <user>1</user>
            <guest>0</guest>
            <staff>1</staff>
            <module>user</module>
            <ordering>0</ordering>
            <value>can_use_2step_verification</value>
        </setting>
    </user_group_settings>
    <settings>
        <setting>
            <group>registration</group>
            <module_id>user</module_id>
            <is_hidden>0</is_hidden>
            <type>boolean</type>
            <var_name>required_strong_password</var_name>
            <phrase_var_name>setting_required_strong_password</phrase_var_name>
            <ordering>58</ordering>
            <version_id>4.8.9</version_id>
            <value>0</value>
        </setting>
        <setting>
            <group>registration</group>
            <module_id>user</module_id>
            <is_hidden>0</is_hidden>
            <type>integer</type>
            <var_name>min_length_for_password</var_name>
            <phrase_var_name>setting_min_length_for_password</phrase_var_name>
            <ordering>59</ordering>
            <version_id>4.8.9</version_id>
            <value>6</value>
        </setting>
        <setting>
            <group>registration</group>
            <module_id>user</module_id>
            <is_hidden>0</is_hidden>
            <type>integer</type>
            <var_name>max_length_for_password</var_name>
            <phrase_var_name>setting_max_length_for_password</phrase_var_name>
            <ordering>60</ordering>
            <version_id>4.8.9</version_id>
            <value>32</value>
        </setting>
    </settings>
</upgrade>